<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Assets\Styles\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\DingTalk-JinBuTi.ttf" />
    <Resource Include="Assets\Fonts\iconfont.ttf" />
    <Resource Include="Assets\Images\a1.png" />
    <Resource Include="Assets\Images\a2.png" />
    <Resource Include="Assets\Images\a3.png" />
    <Resource Include="Assets\Images\a4.png" />
    <Resource Include="Assets\Images\b1.png" />
    <Resource Include="Assets\Images\b2.png" />
    <Resource Include="Assets\Images\b3.png" />
    <Resource Include="Assets\Images\d1.png" />
    <Resource Include="Assets\Images\d2.png" />
    <Resource Include="Assets\Images\d3.png" />
    <Resource Include="Assets\Images\d4.png" />
    <Resource Include="Assets\Images\Logo_64.png" />
  </ItemGroup>

</Project>
